name: Run Karma Tests

on:
  push:
    branches:
      - main

jobs:
  karma-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm install --force

      - name: Run Karma Tests
        run: npm test