name: Run Karma Tests

on:
  push:
    branches:
      - main

jobs:
  karma-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm install --f

      - name: Run Karma Tests
        run: npm test